export const ARTICLES = '/articles'
export const ARTICLES_SLUG = '/articles/:slug'
export const SIGN_UP = '/sign-up'
export const SIGN_IN = '/sign-in'
export const PROFILE = '/profile'
export const NEW_ARTICLE = '/new-article'
export const ARTICLES_SLUG_EDIT = '/articles/:slug/edit'
export const NOT_FOUND = '*'
